name: comment-triggered
on:
  issue_comment:
    types: created

env:
  BODY: /test
jobs:
    if: ${{ contains(github.event.comment.html_url, '/pull/') && startsWith(github.event.comment.body, '!build') }}
  pull-request-job:
    name: Build and Publish
    env:
      PR_NUMBER: ${{ github.event.issue.number }}
      TEST_PR_NUMBER: PR-${{ github.event.issue.number }}
    environment:
      name: dev
      url: https://github.com/gravicore/sbx-jon.engene-public/pull/${{ env.PR_NUMBER }}
    if: contains(github.event.comment.html_url, '/pull/')    # check if the comments come from pull request, exclude those from issue.
    runs-on: [ubuntu-latest]
    steps:
      - name: comment support
        if: contains(github.event.comment.body, '/support')   # check the comment if it contains the keywords
        run: |
          echo say test
      - name: test
        if: contains(${{ env.BODY }}, '/test')  # check the comment if it contains the keywords
        run: |
          echo "This test step should always run"
      - name: build example
        if: startsWith(github.event.comment.body, '!build')  # check the comment if it contains the keywords
        run: |
          echo this is the build
      - name:
        run: |
          echo PR TAG:${{ env.TEST_PR_NUMBER }}
          