name: comment-triggered
on:
  issue_comment:                                     
    types: created
jobs:
  pull-request-job:
  env:
    PR_NUMBER: PR-${{ github.event.number }}
  environment:
    name: dev
    url: $PR_NUMBER
    if: contains(github.event.comment.html_url, '/pull/')    # check if the comments come from pull request, exclude those from issue.
    runs-on: [ubuntu-latest]
    steps:
      - name: comment support
        if: contains(github.event.comment.body, '/support')   # check the comment if it contains the keywords
        run: |
          echo say test
      - name: test
        if: contains(github.event.comment.body, '/test')  # check the comment if it contains the keywords
        run: |
          echo test
      - name: build example
        if: startsWith(github.event.comment.body, '!build')  # check the comment if it contains the keywords
        run: |
          echo this is the build
