name: Workflow A

on:
  pull_request:
    paths:
      - '**/*'

jobs:
  jobA:
    runs-on: ubuntu-latest

    steps:
      - name: Set environment variable
        run: echo "MY_VARIABLE=example_value" >> $GITHUB_ENV

      - name: Create text file
        run: echo "MY_VARIABLE=${MY_VARIABLE}" > my-file.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: my-file.txt
